/*
  app.js — simplified, repaired dashboard renderer
  Replaced truncated implementation with a robust, smaller renderer that
  reads window.DASHBOARD_DATA, validates it, and renders a usable dashboard.

  Changes made on branch: upgrade/fixes-2026-05-12
  Generated by GitHub Copilot via ChatGPT on 2026-05-12.
*/
(function () {
  'use strict';

  var NOTES_KEY = "fd_audit_notes_v1";

  function log() { if (window.DEBUG_FD) console.debug.apply(console, arguments); }

  function escapeHtml(s) {
    if (s === null || s === undefined) return "";
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function pad2(n) { return (n < 10 ? "0" : "") + n; }

  function todayKey() {
    var t = new Date();
    return t.getFullYear() + "-" + pad2(t.getMonth() + 1) + "-" + pad2(t.getDate());
  }

  function parseDateKey(d) {
    if (!d) return null;
    // Accept YYYY-MM-DD or Date
    if (d instanceof Date) return new Date(d.getFullYear(), d.getMonth(), d.getDate());
    var parts = String(d).split(/[-T ]/)[0].split("-");
    if (parts.length !== 3) return null;
    return new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
  }

  function formatDateLong(d) {
    var dt = parseDateKey(d);
    if (!dt) return "";
    return dt.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
  }

  function createCalendarHref(item, location) {
    if (!item || !item.date) return "";
    var title = item.title || "Family Dashboard item";
    var text = (item.notes || '') + (item.source && item.source.summary ? '\n\n' + item.source.summary : '');
    var where = (location && (location.name || location.address)) ? (location.name || location.address) : '';
    // Google Calendar expects YYYYMMDD or YYYYMMDDTHHMMSSZ. We'll provide local times without Z.
    var start, end;
    var date = String(item.date).replace(/-/g, '');
    if (item.startTime) {
      var s = String(item.startTime).replace(/:/g, '');
      start = date + 'T' + (s.length === 4 ? s + '00' : s);
      if (item.endTime) {
        var e = String(item.endTime).replace(/:/g, '');
        end = date + 'T' + (e.length === 4 ? e + '00' : e);
      } else {
        // default 1-hour duration
        end = start.slice(0, 9) + String(Number(start.slice(9, 13)) + 100) + '00';
      }
    } else {
      // all-day: use YYYYMMDD/YYYYMMDD
      start = date;
      end = date;
    }
    var params = [];
    params.push('action=TEMPLATE');
    params.push('text=' + encodeURIComponent(title));
    if (text) params.push('details=' + encodeURIComponent(text));
    if (where) params.push('location=' + encodeURIComponent(where));
    params.push('dates=' + encodeURIComponent(start + '/' + end));
    return 'https://calendar.google.com/calendar/render?' + params.join('&');
  }

  function validateDashboardData(raw) {
    var errors = [];
    if (!raw) { errors.push('No data supplied'); return { ok: false, errors: errors }; }
    if (!raw.meta) errors.push('Missing meta');
    if (!Array.isArray(raw.children)) errors.push('Missing children array');
    if (!Array.isArray(raw.items)) errors.push('Missing items array');
    if (errors.length) return { ok: false, errors: errors };
    return { ok: true };
  }

  function buildModel(raw) {
    var model = { meta: raw.meta || {}, children: raw.children || [], categories: raw.categories || [], items: [] };
    (raw.items || []).forEach(function (it, idx) {
      var copy = Object.assign({}, it);
      copy._index = idx;
      // normalize date key
      copy._dateObj = parseDateKey(copy.date);
      copy._dateKey = copy.date || null;
      copy._timeSort = copy.startTime ? (String(copy.startTime) + (copy.endTime || '')) : 'zzzz';
      model.items.push(copy);
    });
    // sort
    model.items.sort(function (a, b) {
      if (!a._dateKey && !b._dateKey) return 0;
      if (!a._dateKey) return 1;
      if (!b._dateKey) return -1;
      if (a._dateKey < b._dateKey) return -1;
      if (a._dateKey > b._dateKey) return 1;
      // same date: compare startTime
      if ((a.startTime || '') < (b.startTime || '')) return -1;
      if ((a.startTime || '') > (b.startTime || '')) return 1;
      return 0;
    });
    return model;
  }

  function renderTopNav(model, container) {
    var kids = model.children || [];
    var kidHtml = kids.map(function (k) {
      return '<button class="nav-pill kid-' + escapeHtml(k.colorKey || 'gold') + '" data-kid="' + escapeHtml(k.id) + '">' + escapeHtml(k.displayName) + '</button>';
    }).join('\n');
    var catHtml = (model.categories || []).filter(function(c){return c.visible !== false}).map(function (c){
      return '<button class="chip" data-cat="' + escapeHtml(c.id) + '">' + escapeHtml(c.label) + '</button>';
    }).join('\n');
    container.innerHTML = '\n      <div class="top-nav glass-panel">\n        <a class="brand-mark" href="#"><span>FD</span><strong>Family Desk</strong></a>\n        <div class="kid-filter">' + kidHtml + '</div>\n        <div class="category-filter">' + catHtml + '</div>\n      </div>\n    ';
  }

  function renderHero(model, container) {
    // show today and counts
    var today = todayKey();
    var todayItems = model.items.filter(function(it){ return it._dateKey === today; });
    var upcoming = model.items.filter(function(it){ return it._dateKey && it._dateKey >= today; }).slice(0,8);
    var html = '\n      <section class="hero-grid">\n        <div class="glass-panel hero-copy">\n          <p class="eyebrow">Family Dashboard</p>\n          <h1>Today</h1>\n          <div class="deck">Quick view of what matters today.</div>\n          <div class="hero-metrics">\n            <span><b>' + escapeHtml(String(todayItems.length)) + '</b> Today items</span>\n            <span><b>' + escapeHtml(String(upcoming.length)) + '</b> Upcoming</span>\n            <span><b>' + escapeHtml(String(model.items.filter(i=>i.priority==='urgent').length)) + '</b> Urgent</span>\n            <span><b>' + escapeHtml(String(model.items.length)) + '</b> Total</span>\n          </div>\n        </div>\n        <aside class="glass-panel forward-card">\n          <h2>Upcoming</h2>\n          <div class="mini-meta">' + upcoming.map(function(it){
            return '<button class="mini-card accent-' + escapeHtml(it.priority || 'amber') + '" data-open-item="' + escapeHtml(it.id) + '"><span>' + escapeHtml(it.startTime || '') + '</span><strong>' + escapeHtml(it.title) + '</strong><em>' + escapeHtml(it._dateKey || 'TBD') + '</em></button>';
          }).join('\n') + '</div>\n        </aside>\n      </section>\n    ';
    container.innerHTML = html;
  }

  function renderMain(model, container) {
    var today = todayKey();
    var byDate = {};
    model.items.forEach(function (it) {
      var k = it._dateKey || 'unscheduled';
      byDate[k] = byDate[k] || [];
      byDate[k].push(it);
    });
    var keys = Object.keys(byDate).sort(function(a,b){ if (a==='unscheduled') return 1; if (b==='unscheduled') return -1; return a < b ? -1 : (a>b?1:0); });
    var html = '<div class="content-grid">\n  <div class="event-column">';
    keys.forEach(function (k) {
      html += '<div class="section-heading"><h2>' + (k==='unscheduled' ? 'Unscheduled' : formatDateLong(k)) + '</h2></div>';
      byDate[k].forEach(function (it) {
        html += '<article class="event-card accent-'+ escapeHtml(it.priority || 'amber') + '" data-open-item="' + escapeHtml(it.id) + '">\n          <div class="event-rail"><span></span></div>\n          <div class="event-main">\n            <div class="event-topline"><span class="category-pill">' + escapeHtml(it.category || '') + '</span><span>' + escapeHtml(it.childNames ? it.childNames.join(', ') : '') + '</span></div>\n            <h3>' + escapeHtml(it.title) + '</h3>\n            <p class="summary-line">' + escapeHtml(it.notes || (it.source && it.source.summary) || '') + '</p>\n            <div class="badge-row">' + (it.actionNeeded && it.actionNeeded.required ? ('<span class="badge warn"><b>Action:</b>' + escapeHtml(it.actionNeeded.label || 'Action required') + '</span>') : '') + '</div>\n            <div class="card-links">' + (it.date ? '<a href="'+ createCalendarHref(it, it.location) + '" target="_blank">Add to calendar</a>' : '') + '<span>' + escapeHtml(it.source && it.source.sender || '') + '</span></div>\n          </div>\n        </article>';
      });
    });
    html += '</div>\n  <aside class="side-column">\n    <section class="glass-panel today-brief">\n      <h2>Today</h2>\n      <div id="today-list">';
    var todayItems = model.items.filter(function(it){ return it._dateKey === today; });
    if (!todayItems.length) html += '<p class="muted">No items for today.</p>';
    todayItems.forEach(function(it){
      html += '<div class="calendar-row"><strong>' + escapeHtml(it.title) + '</strong><div>' + escapeHtml(it.startTime || '') + ' ' + escapeHtml(it.location && it.location.name || '') + '</div></div>';
    });
    html += '</div></section>\n    <section class="glass-panel source-ledger">\n      <h2>Sources</h2>\n      <div class="muted source-range">' + escapeHtml(model.meta && model.meta.sourceTypesReviewed ? model.meta.sourceTypesReviewed.join(', ') : '') + '</div>\n    </section>\n  </aside>\n</div>';

    container.innerHTML = html;
  }

  function openOverlay(item, model) {
    var backdrop = document.createElement('div');
    backdrop.className = 'overlay-backdrop';
    backdrop.innerHTML = '<div class="detail-overlay glass-panel" role="dialog" aria-modal="true" aria-labelledby="overlay-title">\n      <button class="close-overlay" aria-label="Close overlay">×</button>\n      <h2 id="overlay-title">' + escapeHtml(item.title) + '</h2>\n      <div class="overlay-summary">' + escapeHtml(item.notes || (item.source && item.source.summary) || '') + '</div>\n      <div class="overlay-facts fact-grid">\n        <div><dt>Date</dt><dd>' + escapeHtml(item._dateKey || 'Unscheduled') + '</dd></div>\n        <div><dt>When</dt><dd>' + escapeHtml(item.startTime || '—') + '</dd></div>\n      </div>\n      <div class="card-links">' + (item.date ? '<a href="'+ createCalendarHref(item, item.location) + '" target="_blank">Open in Calendar</a>' : '') + '<button id="add-note-btn">Add note</button></div>\n    </div>';
    document.body.appendChild(backdrop);
    var closeBtn = backdrop.querySelector('.close-overlay');
    function close() { document.body.removeChild(backdrop); lastFocused && lastFocused.focus(); }
    closeBtn.addEventListener('click', close);
    backdrop.addEventListener('click', function (e) { if (e.target === backdrop) close(); });
    document.addEventListener('keydown', function escHandler(e){ if (e.key === 'Escape') { close(); document.removeEventListener('keydown', escHandler); } });
    // focus management
    var lastFocused = document.activeElement;
    var focusable = backdrop.querySelector('button, a, [tabindex]');
    if (focusable) focusable.focus();

    // add-note
    var addBtn = backdrop.querySelector('#add-note-btn');
    if (addBtn) addBtn.addEventListener('click', function () {
      var text = prompt('Add an audit note for this item:');
      if (!text) return;
      var notes = getAuditNotes();
      notes.unshift({ id: 'n_' + Date.now(), itemId: item.id, text: text, createdAt: new Date().toISOString() });
      saveAuditNotes(notes);
      alert('Saved note.');
    });
  }

  function attachEvents(model) {
    document.body.addEventListener('click', function (e) {
      var open = e.target.closest('[data-open-item]');
      if (open) {
        var id = open.getAttribute('data-open-item');
        var item = model.items.find(function (it) { return it.id === id; });
        if (item) openOverlay(item, model);
      }
    });
  }

  function localStorageOk() {
    try { localStorage.setItem('__fd_test__', '1'); localStorage.removeItem('__fd_test__'); return true; }
    catch (e) { return false; }
  }

  function getAuditNotes() {
    try { var raw = localStorage.getItem(NOTES_KEY); return raw ? JSON.parse(raw) : []; } catch (e) { return []; }
  }

  function saveAuditNotes(notes) {
    try { localStorage.setItem(NOTES_KEY, JSON.stringify(notes)); return true; } catch (e) { return false; }
  }

  function renderApp() {
    var root = document.getElementById('root');
    if (!root) { console.error('No root element found'); return; }
    var raw = window.DASHBOARD_DATA;
    var validation = validateDashboardData(raw);
    if (!validation.ok) {
      root.innerHTML = '<section class="data-error-panel glass-panel"><h1>Data error</h1><p>' + escapeHtml(validation.errors.join('; ')) + '</p></section>';
      return;
    }
    var model = buildModel(raw);
    // build container
    var container = document.createElement('div');
    container.className = 'family-desk';
    // top nav
    var top = document.createElement('div');
    renderTopNav(model, top);
    container.appendChild(top);
    // hero
    var heroWrap = document.createElement('div');
    renderHero(model, heroWrap);
    container.appendChild(heroWrap);
    // main
    var mainWrap = document.createElement('div');
    renderMain(model, mainWrap);
    container.appendChild(mainWrap);

    // notes panel if no localStorage
    if (!localStorageOk()) {
      var notePanel = document.createElement('div');
      notePanel.className = 'glass-panel data-error-panel';
      notePanel.innerHTML = '<h2>Notes unavailable</h2><p>localStorage is not available in this browser. Notes will not be saved.</p>';
      container.appendChild(notePanel);
    }

    root.innerHTML = '';
    root.appendChild(container);
    attachEvents(model);
    log('Rendered model with', model.items.length, 'items');
  }

  // On DOM ready
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', renderApp); else renderApp();

})();
