// FAMILY DASHBOARD MANUAL DATA FILE
// Generated by ChatGPT on 2026-05-11T15:55:00-04:00.
// Replace this whole file when ChatGPT generates updated dashboard data.
// This file must define window.DASHBOARD_DATA and must not use module loaders or network calls.
window.DASHBOARD_DATA = {
  "meta": {
    "schemaVersion": "1.0.0",
    "generatedAt": "2026-05-11T15:55:00-04:00",
    "generatedBy": "ChatGPT manual extraction task",
    "dataMode": "manual_file",
    "timezone": "America/New_York",
    "sourceWindow": {
      "startDate": "2026-04-23",
      "endDate": "2026-08-31"
    },
    "sourceTypesReviewed": [
      "gmail",
      "calendar"
    ],
    "dashboardInstructions": {
      "defaultView": "today",
      "showNeedsReviewFirst": true,
      "hideArchivedByDefault": true
    }
  },
  "children": [
    {
      "id": "lily",
      "displayName": "Lily",
      "colorKey": "purple",
      "active": true
    },
    {
      "id": "cole",
      "displayName": "Cole",
      "colorKey": "blue",
      "active": true
    }
  ],
  "categories": [
    {
      "id": "school",
      "label": "School",
      "visible": true
    },
    {
      "id": "dance",
      "label": "Dance",
      "visible": true
    },
    {
      "id": "theater",
      "label": "Theater",
      "visible": true
    },
    {
      "id": "sports",
      "label": "Sports",
      "visible": true
    },
    {
      "id": "family",
      "label": "Family",
      "visible": true
    },
    {
      "id": "other",
      "label": "Other",
      "visible": false
    }
  ],
  "items": [
    {
      "id": "school_pe_swim_unit_20260511",
      "type": "event",
      "title": "WGCSD PE Swim Unit",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-11",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "WGCSD",
        "address": null,
        "notes": "Runs on days Lily has PE class."
      },
      "source": {
        "sourceType": "gmail",
        "summary": "3rd-6th grade Swim Units begin Monday, May 11 and run through June 5. Students swim on days they have PE class and should bring a swimsuit, towel, and bag.",
        "sender": "WGCSD Alerts <wgcsd@wgcsd.org>",
        "receivedAt": "2026-05-08T14:12:03-04:00",
        "subject": "3-6th Grade PE Swim Unit Reminder",
        "link": "https://mail.google.com/mail/#all/19e08cb1b9b45b5a",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Send swimsuit, towel, and bag on PE/swim days.",
        "dueDate": null,
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Swimsuit",
          "status": "needed"
        },
        {
          "label": "Towel",
          "status": "needed"
        },
        {
          "label": "Bag for wet items",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_on_calendar",
      "priority": "urgent",
      "reviewStatus": "ready",
      "notes": "Calendar checked against Kids Calendar; swim unit was not found as a listed event.",
      "tags": [
        "school",
        "swim",
        "PE",
        "active-now"
      ]
    },
    {
      "id": "school_parent_engagement_ice_cream_20260519",
      "type": "event",
      "title": "Ice Cream with the Counselors",
      "category": "school",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-05-19",
      "startTime": "17:30",
      "endTime": "18:30",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Cafe 1",
        "address": null,
        "notes": "Enter at side door near cafeteria."
      },
      "source": {
        "sourceType": "gmail",
        "summary": "Parent engagement event with Ms. Bresett and Mrs. Theetge focused on helping children build coping skills and manage big emotions.",
        "sender": "Christin Bresett <cbresett@wgcsd.org>",
        "receivedAt": "2026-05-04T14:31:13-04:00",
        "subject": "FW: Parent Engagement Event",
        "link": "https://mail.google.com/mail/#all/19df4423dc810eff",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "RSVP if planning to attend.",
        "dueDate": "2026-05-15",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "RSVP form",
          "status": "needed"
        },
        {
          "label": "Any questions about coping strategies",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "RSVP link was included in the email: https://forms.cloud.microsoft/r/YVcb3qd0ve",
      "tags": [
        "school",
        "parent-event",
        "RSVP",
        "coping-skills"
      ]
    },
    {
      "id": "school_spring_concert_20260527",
      "type": "event",
      "title": "3rd-6th Grade Spring Concert",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-27",
      "startTime": "18:30",
      "endTime": "20:00",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "High School Auditorium",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "gmail",
        "summary": "Spring concert for grades 3-6 is Wednesday, May 27 at 6:30 PM. No school-day dress rehearsal this year, so attendance is extra important.",
        "sender": "Madelyn Houck <MAHOUCK@wgcsd.org>",
        "receivedAt": "2026-05-01T13:27:02-04:00",
        "subject": "3rd-6th Grade Spring Concert 🌷🎵",
        "link": "https://mail.google.com/mail/#all/19de4949c5cb580e",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Make sure Lily attends the evening concert.",
        "dueDate": "2026-05-27",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Concert outfit/details when sent",
          "status": "needed"
        },
        {
          "label": "Arrival time confirmation",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "Kids Calendar contains this event from 6:30 PM to 8:00 PM.",
      "tags": [
        "school",
        "concert",
        "music",
        "calendar-confirmed"
      ]
    },
    {
      "id": "school_volunteer_fun_day_2026",
      "type": "task",
      "title": "WGES End-of-Year Fun Day Volunteers",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": null,
      "startTime": null,
      "endTime": null,
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Watkins Glen Elementary School",
        "address": null,
        "notes": "Main office handles volunteer form turn-in."
      },
      "source": {
        "sourceType": "gmail",
        "summary": "WGES needs volunteers for end-of-year fun day. Interested parents should fill out the Volunteer Form and turn it into the main office.",
        "sender": "Watkins Glen Elementary School <wges@wgcsd.org>",
        "receivedAt": "2026-05-05T12:23:05-04:00",
        "subject": "Seeking Volunteers!",
        "link": "https://mail.google.com/mail/#all/19df8f4393235410",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Fill out and return Volunteer Form if you want to volunteer.",
        "dueDate": null,
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Volunteer Form",
          "status": "needed"
        }
      ],
      "calendarStatus": "needs_review",
      "priority": "medium",
      "reviewStatus": "needs_review",
      "notes": "Email did not include the event date in readable text.",
      "tags": [
        "school",
        "volunteer",
        "needs-review"
      ]
    },
    {
      "id": "school_thoughtful_placement_2026_2027",
      "type": "task",
      "title": "2026-2027 Thoughtful Placement Form",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": null,
      "startTime": null,
      "endTime": null,
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Watkins Glen Elementary School",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "gmail",
        "summary": "WGES shared a parent/guardian input opportunity for 2026-2027 placement. The form is for learning style and other useful student information, not teacher requests.",
        "sender": "Watkins Glen Elementary School <wges@wgcsd.org>",
        "receivedAt": "2026-05-04T13:33:48-04:00",
        "subject": "Parent/Guardian Input Opportunity 2026-2027",
        "link": "https://mail.google.com/mail/#all/19df40dbe69af7f6",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Complete thoughtful placement form if you want to provide placement input.",
        "dueDate": null,
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Learning style notes",
          "status": "needed"
        },
        {
          "label": "Behavioral/academic/family input",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_applicable",
      "priority": "medium",
      "reviewStatus": "needs_review",
      "notes": "No deadline found in readable email text.",
      "tags": [
        "school",
        "form",
        "placement",
        "needs-review"
      ]
    },
    {
      "id": "school_summer_playground_2026",
      "type": "task",
      "title": "WGES Summer Playground Registration",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": null,
      "startTime": "08:00",
      "endTime": "12:00",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Watkins Glen Elementary School",
        "address": null,
        "notes": "Summer Playground runs Monday-Thursday. Specific program dates were not included in readable email text."
      },
      "source": {
        "sourceType": "gmail",
        "summary": "WGES Summer Playground program will run Monday-Thursday from 8 AM to 12 PM. Breakfast, lunch, and transportation are provided. Online registration form is available.",
        "sender": "Watkins Glen Elementary School <wges@wgcsd.org>",
        "receivedAt": "2026-05-04T07:35:52-04:00",
        "subject": "WGES Summer Playground",
        "link": "https://mail.google.com/mail/#all/19df2c67a4bc8175",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Register Lily if you want her enrolled in Summer Playground.",
        "dueDate": null,
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Online registration form",
          "status": "needed"
        },
        {
          "label": "Contact Jana Reidy at jareidy@gstboces.org if questions",
          "status": "needed"
        }
      ],
      "calendarStatus": "needs_review",
      "priority": "medium",
      "reviewStatus": "needs_review",
      "notes": "Specific program start/end dates were not visible in the email body.",
      "tags": [
        "school",
        "summer",
        "registration",
        "needs-review"
      ]
    },
    {
      "id": "sports_youth_basketball_camp_2026",
      "type": "task",
      "title": "Watkins Glen Youth Basketball Camp",
      "category": "sports",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": null,
      "startTime": null,
      "endTime": null,
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Watkins Glen",
        "address": null,
        "notes": "Camp details not fully included in email text."
      },
      "source": {
        "sourceType": "gmail",
        "summary": "Registration is open for Watkins Glen Youth Basketball Camp for students entering grades 2nd-6th. Coach Learn is the contact for questions.",
        "sender": "Watkins Glen Elementary School <wges@wgcsd.org>",
        "receivedAt": "2026-05-09T08:21:36-04:00",
        "subject": "Watkins Glen Youth Basketball Camp",
        "link": "https://mail.google.com/mail/#all/19e0cb021b754884",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Review/register if Lily is interested in basketball camp.",
        "dueDate": null,
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Registration details",
          "status": "needed"
        },
        {
          "label": "Questions for Coach Learn",
          "status": "needed"
        }
      ],
      "calendarStatus": "needs_review",
      "priority": "medium",
      "reviewStatus": "needs_review",
      "notes": "Readable email did not include camp dates/times.",
      "tags": [
        "sports",
        "basketball",
        "camp",
        "registration",
        "needs-review"
      ]
    },
    {
      "id": "theater_finding_nemo_fee_clothing_20260619",
      "type": "task",
      "title": "Finding Nemo Jr — Fee and Clothing Form",
      "category": "theater",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-06-19",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "Lake Country Players rehearsal",
        "address": null,
        "notes": "Lorry Johnson is collecting fees/forms during the first half hour of rehearsals."
      },
      "source": {
        "sourceType": "gmail",
        "summary": "Participation fee is $20 for the first child. Clothing form attached for Finding Nemo shirts/sweatshirts. Lorry plans to collect fees and clothing forms during rehearsals.",
        "sender": "Lake Country Players <lakecountryplayers@gmail.com>",
        "receivedAt": "2026-05-06T16:27:04-04:00",
        "subject": "All Things Nemo",
        "link": "https://mail.google.com/mail/#all/19dfef9312650902",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Pay $20 participation fee and submit clothing order form if ordering Nemo clothing.",
        "dueDate": "2026-06-19",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "$20 participation fee",
          "status": "needed"
        },
        {
          "label": "Clothing Form.docx",
          "status": "needed"
        },
        {
          "label": "Confirm email order if submitted by email",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_applicable",
      "priority": "high",
      "reviewStatus": "needs_review",
      "notes": "Email did not state a written due date in readable body, but previous dashboard design tracked June 19 as the clothing/fee deadline. Keep as needs-verification if uncertain.",
      "tags": [
        "theater",
        "Finding Nemo",
        "fee",
        "clothing",
        "Lake Country Players"
      ]
    },
    {
      "id": "dance_recital_semester_week4_20260506",
      "type": "info",
      "title": "Dance Recital Semester — Week 4 Update",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-18",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "Leslie School of Dance",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "gmail",
        "summary": "Recital semester update: 2 more weeks of class, 3 weeks until performances, final classes end May 23, costumes go home week of May 18 if account balance is zero.",
        "sender": "Leslie School of Dance <no-reply@dancestudio-pro.com>",
        "receivedAt": "2026-05-06T09:06:49-04:00",
        "subject": "2025-2026 Season - Recital Semester - Wek 4",
        "link": "https://mail.google.com/mail/#all/19dfd66063e86b29",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Check account balance, costume details, shoes, hair style, ticketing, recital website, and volunteer needs.",
        "dueDate": "2026-05-18",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Account balance must be 0 for costumes to go home",
          "status": "needed"
        },
        {
          "label": "Review costume description in parent portal",
          "status": "needed"
        },
        {
          "label": "Check shoes and hair style",
          "status": "needed"
        },
        {
          "label": "Review ticketing link",
          "status": "needed"
        },
        {
          "label": "Review recital website/newsletter",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_applicable",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "Information station hours: May 18 5-7 PM, May 19 4:30-6 PM, May 20 4-7 PM, May 21 4-7 PM, May 23 10-12 PM.",
      "tags": [
        "dance",
        "recital",
        "costumes",
        "tickets",
        "parent-portal"
      ]
    },
    {
      "id": "dance_bring_stuffy_week_20260511",
      "type": "reminder",
      "title": "Dance — Bring a Stuffy to Class Week",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-11",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "Leslie School of Dance",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "gmail",
        "summary": "May 11-16 is Bring your 'stuffy' to class week to help students practice performing for an audience.",
        "sender": "Leslie School of Dance <no-reply@dancestudio-pro.com>",
        "receivedAt": "2026-05-06T09:06:49-04:00",
        "subject": "2025-2026 Season - Recital Semester - Wek 4",
        "link": "https://mail.google.com/mail/#all/19dfd66063e86b29",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Send Lily with a stuffed animal/doll/non-living audience item for dance class.",
        "dueDate": "2026-05-13",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Stuffy/doll for class",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_applicable",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "Applies during regular class week May 11-16.",
      "tags": [
        "dance",
        "recital",
        "stuffy",
        "this-week"
      ]
    },
    {
      "id": "dance_show_week_costumes_20260518",
      "type": "reminder",
      "title": "Dance — Show Week and Costume Take-Home",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-18",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "Leslie School of Dance",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "gmail",
        "summary": "May 18-23 is Show Week and costume take-home week. Costumes go home as long as the account has a $0 balance.",
        "sender": "Leslie School of Dance <no-reply@dancestudio-pro.com>",
        "receivedAt": "2026-05-06T09:06:49-04:00",
        "subject": "2025-2026 Season - Recital Semester - Wek 4",
        "link": "https://mail.google.com/mail/#all/19dfd66063e86b29",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Confirm account balance is zero so costumes can go home.",
        "dueDate": "2026-05-18",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Check parent portal balance",
          "status": "needed"
        },
        {
          "label": "Prepare for costumes coming home",
          "status": "needed"
        },
        {
          "label": "Review hair/shoes/costume description",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_applicable",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "Saturdays may receive costumes May 16.",
      "tags": [
        "dance",
        "costumes",
        "show-week",
        "account-balance"
      ]
    },
    {
      "id": "dance_flower_presale_deadline_20260518",
      "type": "task",
      "title": "Dance Recital Flowers Presale Deadline",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-18",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "Leslie School of Dance / online",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "gmail",
        "summary": "Recital flower presale deadline is May 18. Flowers are optional recital gifts.",
        "sender": "Leslie School of Dance <no-reply@dancestudio-pro.com>",
        "receivedAt": "2026-05-06T09:06:49-04:00",
        "subject": "2025-2026 Season - Recital Semester - Wek 4",
        "link": "https://mail.google.com/mail/#all/19dfd66063e86b29",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Order recital flowers by May 18 if you want them.",
        "dueDate": "2026-05-18",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Decide whether to buy flowers/gift",
          "status": "needed"
        }
      ],
      "calendarStatus": "not_applicable",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "Optional.",
      "tags": [
        "dance",
        "flowers",
        "optional",
        "deadline"
      ]
    },
    {
      "id": "dance_finale_opening_rehearsal_20260516",
      "type": "event",
      "title": "Finale Opening Rehearsal",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-16",
      "startTime": "12:00",
      "endTime": "13:30",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Elmira Heights Studio",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Finale opening rehearsal at Elmira Heights Studio.",
        "sender": null,
        "receivedAt": null,
        "subject": "Finale opening rehearsal",
        "link": "https://www.google.com/calendar/event?eid=djRicDQzZGRvdm4yMHZuYXIzMmk4anEyN3MgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "dance",
        "rehearsal",
        "calendar-confirmed"
      ]
    },
    {
      "id": "dance_acro3_practice_20260513",
      "type": "event",
      "title": "Acro3 Lily Dance Practice",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-13",
      "startTime": "17:45",
      "endTime": "18:45",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Leslie School of Dance - Watkins Glen",
        "address": "317 N Franklin St, Watkins Glen, NY 14891",
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: regular Acro3 Lily dance practice.",
        "sender": null,
        "receivedAt": null,
        "subject": "Acro3 Lily Dance Practice",
        "link": "https://www.google.com/calendar/event?eid=NXB2NThuYmlwanNoOW9tOWprb3VvNWdpZGcgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Bring dance gear and stuffy for audience week.",
        "dueDate": "2026-05-13",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Dance gear",
          "status": "needed"
        },
        {
          "label": "Stuffy/doll",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "This practice falls during Bring a Stuffy week.",
      "tags": [
        "dance",
        "practice",
        "calendar-confirmed"
      ]
    },
    {
      "id": "dance_acro3_practice_20260520",
      "type": "event",
      "title": "Acro3 Lily Dance Practice",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-20",
      "startTime": "17:45",
      "endTime": "18:45",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Leslie School of Dance - Watkins Glen",
        "address": "317 N Franklin St, Watkins Glen, NY 14891",
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: regular Acro3 Lily dance practice.",
        "sender": null,
        "receivedAt": null,
        "subject": "Acro3 Lily Dance Practice",
        "link": "https://www.google.com/calendar/event?eid=aW81Mm9oOWhxaDc0cG9pa3NnZG4yZW1jbWsgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Bring dance gear; this is during Show Week/costume take-home week.",
        "dueDate": "2026-05-20",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Dance gear",
          "status": "needed"
        },
        {
          "label": "Check costume/account balance status",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "dance",
        "practice",
        "calendar-confirmed"
      ]
    },
    {
      "id": "dance_acro3_practice_20260527",
      "type": "event",
      "title": "Acro3 Lily Dance Practice",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-27",
      "startTime": "17:45",
      "endTime": "18:45",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Leslie School of Dance - Watkins Glen",
        "address": "317 N Franklin St, Watkins Glen, NY 14891",
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: regular Acro3 Lily dance practice.",
        "sender": null,
        "receivedAt": null,
        "subject": "Acro3 Lily Dance Practice",
        "link": "https://www.google.com/calendar/event?eid=aHNnMXQ0aDd1OXB0MWk2OW1haXV2bzUwNjggOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [
        {
          "label": "Dance gear",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "Same evening as the school spring concert; time conflict may need review.",
      "tags": [
        "dance",
        "practice",
        "calendar-confirmed",
        "possible-conflict"
      ]
    },
    {
      "id": "dance_recital_20260530",
      "type": "event",
      "title": "Dance Recital",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-30",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "Clemens Center",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Recital at Clemens Center.",
        "sender": null,
        "receivedAt": null,
        "subject": "Recital",
        "link": "https://www.google.com/calendar/event?eid=bmgwcXJzb2RndTZsbmV2b2Zobzg4djVlZ3MgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Confirm exact show time, tickets, costumes, shoes, hair, makeup, and arrival instructions.",
        "dueDate": "2026-05-30",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Tickets",
          "status": "needed"
        },
        {
          "label": "Costume",
          "status": "needed"
        },
        {
          "label": "Shoes",
          "status": "needed"
        },
        {
          "label": "Hair/makeup",
          "status": "needed"
        },
        {
          "label": "Arrival time",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "needs_review",
      "notes": "Calendar has all-day event; exact performance time still needs confirmation.",
      "tags": [
        "dance",
        "recital",
        "calendar-confirmed",
        "needs-review"
      ]
    },
    {
      "id": "dance_recital_20260531",
      "type": "event",
      "title": "Dance Recital",
      "category": "dance",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-31",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": "Clemens Center",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Recital at Clemens Center.",
        "sender": null,
        "receivedAt": null,
        "subject": "Recital",
        "link": "https://www.google.com/calendar/event?eid=N3JqYmh0b3BnZzQydXB0M29oOWI1bmFyODAgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Confirm whether Lily performs this day and exact show/arrival time.",
        "dueDate": "2026-05-31",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Tickets",
          "status": "needed"
        },
        {
          "label": "Costume",
          "status": "needed"
        },
        {
          "label": "Shoes",
          "status": "needed"
        },
        {
          "label": "Hair/makeup",
          "status": "needed"
        },
        {
          "label": "Arrival time",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "needs_review",
      "notes": "Calendar has all-day event; exact performance time still needs confirmation.",
      "tags": [
        "dance",
        "recital",
        "calendar-confirmed",
        "needs-review"
      ]
    },
    {
      "id": "sports_cole_track_practice_20260511",
      "type": "event",
      "title": "Cole's Track Practice",
      "category": "sports",
      "childIds": [
        "cole"
      ],
      "childNames": [
        "Cole"
      ],
      "date": "2026-05-11",
      "startTime": "14:30",
      "endTime": "16:30",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "High School",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Cole's Track Practice.",
        "sender": null,
        "receivedAt": null,
        "subject": "Cole's Track Practice",
        "link": "https://www.google.com/calendar/event?eid=M3I0NHFlbnFrbjV0MW5rMGJqaXZ1Z3Vha3NfMjAyNjA1MTFUMTgzMDAwWiA5MTRmYmM4YjIzNzIwMzBkNGIxMjA4MjMzZjA1MzQ1MDM0MWRiZGU1ODQzMWZiOWY3MTFlNTZmMWM4OGQxNjkzQGc&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [
        {
          "label": "Track gear",
          "status": "needed"
        },
        {
          "label": "Water bottle",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "urgent",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "sports",
        "track",
        "practice",
        "calendar-confirmed"
      ]
    },
    {
      "id": "sports_cole_track_practice_20260512",
      "type": "event",
      "title": "Cole's Track Practice",
      "category": "sports",
      "childIds": [
        "cole"
      ],
      "childNames": [
        "Cole"
      ],
      "date": "2026-05-12",
      "startTime": "14:30",
      "endTime": "16:30",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "High School",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Cole's Track Practice.",
        "sender": null,
        "receivedAt": null,
        "subject": "Cole's Track Practice",
        "link": "https://www.google.com/calendar/event?eid=M3I0NHFlbnFrbjV0MW5rMGJqaXZ1Z3Vha3NfMjAyNjA1MTJUMTgzMDAwWiA5MTRmYmM4YjIzNzIwMzBkNGIxMjA4MjMzZjA1MzQ1MDM0MWRiZGU1ODQzMWZiOWY3MTFlNTZmMWM4OGQxNjkzQGc&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [
        {
          "label": "Track gear",
          "status": "needed"
        },
        {
          "label": "Water bottle",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "sports",
        "track",
        "practice",
        "calendar-confirmed"
      ]
    },
    {
      "id": "sports_track_meet_20260513",
      "type": "event",
      "title": "WG 7/8 Boys Outdoor Track Meet",
      "category": "sports",
      "childIds": [
        "cole"
      ],
      "childNames": [
        "Cole"
      ],
      "date": "2026-05-13",
      "startTime": "16:30",
      "endTime": "18:30",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Newark Valley High School",
        "address": "Newark Valley, NY",
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: regular season meet. Opponents: Elmira Heights, Notre Dame, Elmira @ Newark Valley.",
        "sender": null,
        "receivedAt": null,
        "subject": "WG 7/8 Boys Outdoor Track Meet",
        "link": "https://www.google.com/calendar/event?eid=XzZkaTNjb2hnNmRoNjhiYjU2cGozY2I5a2M4cTMyYjlwY2RoM2diOWk2b3MzZWM5aTY0czNhcDFqY2wwNnVzMzVkcGdtaWJqY2R0aG0ycjAgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Confirm transportation and meet needs.",
        "dueDate": "2026-05-13",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Track uniform/gear",
          "status": "needed"
        },
        {
          "label": "Water bottle",
          "status": "needed"
        },
        {
          "label": "Snack",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "sports",
        "track",
        "meet",
        "calendar-confirmed"
      ]
    },
    {
      "id": "school_lily_field_trip_boces_20260526",
      "type": "event",
      "title": "Lily Field Trip — Adventure Based Learning / BOCES Campus",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-05-26",
      "startTime": "08:15",
      "endTime": "14:15",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "BOCES Campus",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Lily school field trip. Notes say Lily is bringing a bag lunch from home and school transportation is provided.",
        "sender": null,
        "receivedAt": null,
        "subject": "Lily — Field Trip: Adventure Based Learning / BOCES Campus",
        "link": "https://www.google.com/calendar/event?eid=aGNxYmM0b2hhNWZqbmttMXI2OWUyaXZ1OTQgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Pack Lily a bag lunch from home.",
        "dueDate": "2026-05-26",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Bag lunch",
          "status": "needed"
        },
        {
          "label": "Water bottle",
          "status": "needed"
        },
        {
          "label": "Comfortable shoes",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "School transportation provided.",
      "tags": [
        "school",
        "field-trip",
        "calendar-confirmed",
        "bag-lunch"
      ]
    },
    {
      "id": "school_lily_field_trip_lee_school_20260609",
      "type": "event",
      "title": "Lily Field Trip — Lee School / Montour Falls",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-06-09",
      "startTime": "09:10",
      "endTime": "10:50",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Lee School",
        "address": "Montour Falls",
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Lily school field trip. School transportation is provided.",
        "sender": null,
        "receivedAt": null,
        "subject": "Lily — Field Trip: Lee School / Montour Falls",
        "link": "https://www.google.com/calendar/event?eid=Y2I5NzYwaDJ2MjN2OWlocmNtaWdyNWFodmcgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [
        {
          "label": "Check school reminders closer to date",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "School transportation provided.",
      "tags": [
        "school",
        "field-trip",
        "calendar-confirmed"
      ]
    },
    {
      "id": "school_lily_field_trip_state_park_20260612",
      "type": "event",
      "title": "Lily Field Trip — Watkins Glen State Park Picnic",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-06-12",
      "startTime": "09:00",
      "endTime": "14:15",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Watkins Glen State Park",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Lily school field trip. Notes say Lily is bringing a bag lunch from home and school transportation is provided.",
        "sender": null,
        "receivedAt": null,
        "subject": "Lily — Field Trip: Watkins Glen State Park Picnic",
        "link": "https://www.google.com/calendar/event?eid=czM4YWN0MDNncW4zMzcwZnFqcXUybWNmZ2cgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Pack Lily a bag lunch from home.",
        "dueDate": "2026-06-12",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Bag lunch",
          "status": "needed"
        },
        {
          "label": "Water bottle",
          "status": "needed"
        },
        {
          "label": "Weather-appropriate clothing",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "School transportation provided.",
      "tags": [
        "school",
        "field-trip",
        "calendar-confirmed",
        "bag-lunch"
      ]
    },
    {
      "id": "school_lily_field_trip_catherine_valley_20260617",
      "type": "event",
      "title": "Lily Field Trip — Catherine Valley Trail Scavenger Hunt",
      "category": "school",
      "childIds": [
        "lily"
      ],
      "childNames": [
        "Lily"
      ],
      "date": "2026-06-17",
      "startTime": "09:00",
      "endTime": "11:00",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": "Catherine Valley Trail",
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event: Lily school field trip. School transportation is provided.",
        "sender": null,
        "receivedAt": null,
        "subject": "Lily — Field Trip: Catherine Valley Trail Scavenger Hunt",
        "link": "https://www.google.com/calendar/event?eid=dXI3czMzNGZjNGJvNjVjYWlwdmFqdTRodGsgOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [
        {
          "label": "Comfortable shoes",
          "status": "needed"
        },
        {
          "label": "Water bottle",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "School transportation provided.",
      "tags": [
        "school",
        "field-trip",
        "calendar-confirmed"
      ]
    },
    {
      "id": "school_cole_gettysburg_trip_20260529",
      "type": "event",
      "title": "Cole — Gettysburg 7th Grade Trip",
      "category": "school",
      "childIds": [
        "cole"
      ],
      "childNames": [
        "Cole"
      ],
      "date": "2026-05-29",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": "Time/location not listed on school page calendar import."
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar event imported from Watkins Glen school website. Direct Cole item. Time/location not listed.",
        "sender": null,
        "receivedAt": null,
        "subject": "Cole - Gettysburg 7th Grade Trip",
        "link": "https://www.google.com/calendar/event?eid=XzY4bzNnZDFqNjRybWFiYjY2Z3JqNGI5azZvcTM2YjlwYzhvNmFiOWo2OHBtMmRwazZvcmppcDlrNjkwNjZxMzFlaGpuMHQxZWRobm02b2JjIDkxNGZiYzhiMjM3MjAzMGQ0YjEyMDgyMzNmMDUzNDUwMzQxZGJkZTU4NDMxZmI5ZjcxMWU1NmYxYzg4ZDE2OTNAZw&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Confirm trip time, location, packing needs, and permission/payment status.",
        "dueDate": "2026-05-29",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Trip details",
          "status": "needed"
        },
        {
          "label": "Food/money needs",
          "status": "needed"
        },
        {
          "label": "Permission/payment status",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "needs_review",
      "notes": "Calendar event lacks time/location details.",
      "tags": [
        "school",
        "field-trip",
        "Cole",
        "needs-review"
      ]
    },
    {
      "id": "family_kids_week_20260508",
      "type": "event",
      "title": "Kids Week",
      "category": "family",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-05-08",
      "startTime": "18:00",
      "endTime": "18:00",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": "Runs Friday 6 PM to following Friday 6 PM."
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar recurring custody block from Friday May 8 at 6 PM to Friday May 15 at 6 PM.",
        "sender": null,
        "receivedAt": null,
        "subject": "Kids Week",
        "link": "https://www.google.com/calendar/event?eid=XzZncGphZGo0Y29yajZiYjY2MHE2NmI5a2M0cjZjYmIyNjRxMzRiOW02MHJqZW9wajcwcGplZGhvYzUwNjZxMzFlaGpuMHQxZWRobm02b2JjXzIwMjYwNTA4VDIyMDAwMFogOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "Current kids week active as of generation time.",
      "tags": [
        "family",
        "custody",
        "kids-week",
        "calendar-confirmed"
      ]
    },
    {
      "id": "family_kids_week_20260522",
      "type": "event",
      "title": "Kids Week",
      "category": "family",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-05-22",
      "startTime": "18:00",
      "endTime": "18:00",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": "Runs Friday 6 PM to following Friday 6 PM."
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar recurring custody block from Friday May 22 at 6 PM to Friday May 29 at 6 PM.",
        "sender": null,
        "receivedAt": null,
        "subject": "Kids Week",
        "link": "https://www.google.com/calendar/event?eid=XzZncGphZGo0Y29yajZiYjY2MHE2NmI5a2M0cjZjYmIyNjRxMzRiOW02MHJqZW9wajcwcGplZGhvYzUwNjZxMzFlaGpuMHQxZWRobm02b2JjXzIwMjYwNTIyVDIyMDAwMFogOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "family",
        "custody",
        "kids-week",
        "calendar-confirmed"
      ]
    },
    {
      "id": "school_memorial_day_no_school_20260525",
      "type": "event",
      "title": "Memorial Day — No School",
      "category": "school",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-05-25",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar district holiday, relevant to 4th grade and 7th grade.",
        "sender": null,
        "receivedAt": null,
        "subject": "Memorial Day — No School",
        "link": "https://www.google.com/calendar/event?eid=X2Nvc21hZTlqNzFoMzZiOWk2Y28zY2I5azcwcTM2YjlvNnNvbTRiOXBjNHNtYWRoaTZncG00Y3BqNmwwNjZxMzFlaGpuMHQxZWRobm02b2JjIDkxNGZiYzhiMjM3MjAzMGQ0YjEyMDgyMzNmMDUzNDUwMzQxZGJkZTU4NDMxZmI5ZjcxMWU1NmYxYzg4ZDE2OTNAZw&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "school",
        "no-school",
        "holiday",
        "calendar-confirmed"
      ]
    },
    {
      "id": "family_cole_birthday_20260528",
      "type": "event",
      "title": "Cole Birthday",
      "category": "family",
      "childIds": [
        "cole"
      ],
      "childNames": [
        "Cole"
      ],
      "date": "2026-05-28",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar annual birthday reminder for Cole.",
        "sender": null,
        "receivedAt": null,
        "subject": "Cole Birthday",
        "link": "https://www.google.com/calendar/event?eid=X2NncW04ZDlwNzFnamdiOXA3MWdtOGI5a2NrcjM4YjlwNjhyMzBiOXBjb29tOGRwbWNkZ204b3BoNjUwNjZxMzFlaGpuMHQxZWRobm02b2JjXzIwMjYwNTI4IDkxNGZiYzhiMjM3MjAzMGQ0YjEyMDgyMzNmMDUzNDUwMzQxZGJkZTU4NDMxZmI5ZjcxMWU1NmYxYzg4ZDE2OTNAZw&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Plan/confirm birthday logistics.",
        "dueDate": "2026-05-28",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Birthday plan",
          "status": "needed"
        },
        {
          "label": "Gift/card/cake if needed",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "high",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "family",
        "birthday",
        "calendar-confirmed"
      ]
    },
    {
      "id": "school_juneteenth_no_school_20260619",
      "type": "event",
      "title": "Juneteenth — No School",
      "category": "school",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-06-19",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar district holiday, relevant to 4th grade and 7th grade.",
        "sender": null,
        "receivedAt": null,
        "subject": "Juneteenth — No School",
        "link": "https://www.google.com/calendar/event?eid=XzZzcTM4b2hrNzFoamViYjVjY3M2OGI5azc0cDMwYjlvY2dzbWFiOW82NG8zNnBiMjZzb2oyb2hpNzEwNjZxMzFlaGpuMHQxZWRobm02b2JjIDkxNGZiYzhiMjM3MjAzMGQ0YjEyMDgyMzNmMDUzNDUwMzQxZGJkZTU4NDMxZmI5ZjcxMWU1NmYxYzg4ZDE2OTNAZw&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "school",
        "no-school",
        "holiday",
        "calendar-confirmed"
      ]
    },
    {
      "id": "school_pk6_early_release_20260624",
      "type": "event",
      "title": "PK-6 Early Release / 7-12 Regents",
      "category": "school",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-06-24",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar notes: relevant to 4th grade as early release; 7-12 Regents context for 7th grade.",
        "sender": null,
        "receivedAt": null,
        "subject": "PK–6 Early Release / 7–12 Regents",
        "link": "https://www.google.com/calendar/event?eid=Xzc0b2owcGhrYzRyNmFiOWw3MHEzZ2I5a2NoajZhYmIyYzhwamNiOW82b3AzZ29iNjY1aDMyZHBqY3AwNjZxMzFlaGpuMHQxZWRobm02b2JjIDkxNGZiYzhiMjM3MjAzMGQ0YjEyMDgyMzNmMDUzNDUwMzQxZGJkZTU4NDMxZmI5ZjcxMWU1NmYxYzg4ZDE2OTNAZw&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Confirm pickup/early release logistics for Lily and any Regents schedule impact for Cole.",
        "dueDate": "2026-06-24",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Pickup plan",
          "status": "needed"
        },
        {
          "label": "Regents schedule check",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "needs_review",
      "notes": "Cole impact may differ because event notes say 7-12 Regents.",
      "tags": [
        "school",
        "early-release",
        "regents",
        "needs-review"
      ]
    },
    {
      "id": "school_last_day_early_release_20260625",
      "type": "event",
      "title": "Last Day for Students and Faculty / PK-6 Early Release / 7-12 Regents",
      "category": "school",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-06-25",
      "startTime": null,
      "endTime": null,
      "allDay": true,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": null
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar notes: relevant to 4th grade as last day and early release; 7-12 Regents context for 7th grade.",
        "sender": null,
        "receivedAt": null,
        "subject": "Last Day for Students and Faculty / PK–6 Early Release / 7–12 Regents",
        "link": "https://www.google.com/calendar/event?eid=X2Nvc21jcGI2YzRybThiOW1jZGhqMmI5azZoZ2pjYjlwNjFobWFiYjU2NWhtMm85bDY4czMwZGhoNmgwNjZxMzFlaGpuMHQxZWRobm02b2JjIDkxNGZiYzhiMjM3MjAzMGQ0YjEyMDgyMzNmMDUzNDUwMzQxZGJkZTU4NDMxZmI5ZjcxMWU1NmYxYzg4ZDE2OTNAZw&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": true,
        "label": "Confirm pickup/last-day logistics and any Regents schedule impact.",
        "dueDate": "2026-06-25",
        "assignedTo": "Doug",
        "status": "not_started"
      },
      "prepItems": [
        {
          "label": "Pickup plan",
          "status": "needed"
        },
        {
          "label": "Last day schedule",
          "status": "needed"
        },
        {
          "label": "Regents schedule check",
          "status": "needed"
        }
      ],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "needs_review",
      "notes": "Cole impact may differ because event notes say 7-12 Regents.",
      "tags": [
        "school",
        "last-day",
        "early-release",
        "regents",
        "needs-review"
      ]
    },
    {
      "id": "family_kids_week_20260605",
      "type": "event",
      "title": "Kids Week",
      "category": "family",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-06-05",
      "startTime": "18:00",
      "endTime": "18:00",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": "Runs Friday 6 PM to following Friday 6 PM."
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar recurring custody block from Friday June 5 at 6 PM to Friday June 12 at 6 PM.",
        "sender": null,
        "receivedAt": null,
        "subject": "Kids Week",
        "link": "https://www.google.com/calendar/event?eid=XzZncGphZGo0Y29yajZiYjY2MHE2NmI5a2M0cjZjYmIyNjRxMzRiOW02MHJqZW9wajcwcGplZGhvYzUwNjZxMzFlaGpuMHQxZWRobm02b2JjXzIwMjYwNjA1VDIyMDAwMFogOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "family",
        "custody",
        "kids-week",
        "calendar-confirmed"
      ]
    },
    {
      "id": "family_kids_week_20260619",
      "type": "event",
      "title": "Kids Week",
      "category": "family",
      "childIds": [
        "lily",
        "cole"
      ],
      "childNames": [
        "Lily",
        "Cole"
      ],
      "date": "2026-06-19",
      "startTime": "18:00",
      "endTime": "18:00",
      "allDay": false,
      "timezone": "America/New_York",
      "location": {
        "name": null,
        "address": null,
        "notes": "Runs Friday 6 PM to following Friday 6 PM."
      },
      "source": {
        "sourceType": "calendar",
        "summary": "Kids Calendar recurring custody block from Friday June 19 at 6 PM to Friday June 26 at 6 PM.",
        "sender": null,
        "receivedAt": null,
        "subject": "Kids Week",
        "link": "https://www.google.com/calendar/event?eid=XzZncGphZGo0Y29yajZiYjY2MHE2NmI5a2M0cjZjYmIyNjRxMzRiOW02MHJqZW9wajcwcGplZGhvYzUwNjZxMzFlaGpuMHQxZWRobm02b2JjXzIwMjYwNjE5VDIyMDAwMFogOTE0ZmJjOGIyMzcyMDMwZDRiMTIwODIzM2YwNTM0NTAzNDFkYmRlNTg0MzFmYjlmNzExZTU2ZjFjODhkMTY5M0Bn&ctz=America/New_York",
        "confidence": "confirmed"
      },
      "actionNeeded": {
        "required": false,
        "label": null,
        "dueDate": null,
        "assignedTo": null,
        "status": "not_applicable"
      },
      "prepItems": [],
      "calendarStatus": "on_calendar",
      "priority": "medium",
      "reviewStatus": "ready",
      "notes": "",
      "tags": [
        "family",
        "custody",
        "kids-week",
        "calendar-confirmed"
      ]
    }
  ],
  "review": {
    "overallStatus": "ready_to_upload",
    "warnings": [
      "Some items have needs_review because source email/calendar did not include exact dates, times, or child applicability.",
      "Finding Nemo fee/clothing item uses the dashboard's previously tracked June 19 deadline plus the latest Lake Country Players email details; verify if needed.",
      "Dance recital all-day calendar events do not include exact show/arrival times."
    ],
    "unknowns": [
      "Exact WGES End-of-Year Fun Day date was not visible in the read email text.",
      "Exact WGES Summer Playground start/end dates were not visible in the read email text.",
      "Exact Watkins Glen Youth Basketball Camp dates/times were not visible in the read email text.",
      "Exact dance recital performance times and Lily-specific show assignments need confirmation."
    ],
    "excludedItems": [
      {
        "reason": "Excluded noise",
        "summary": "Bark alerts and forwarded Bark messages were excluded unless they contained real event/action information."
      },
      {
        "reason": "Excluded noise",
        "summary": "ChatGPT task update emails were excluded."
      },
      {
        "reason": "Excluded noise",
        "summary": "Promotional/unrelated emails from Temu, NewsBreak, Rocket Money, Disney+, Uber, Klarna, and GitHub/Codex notifications were excluded."
      },
      {
        "reason": "Excluded non-action safety drill notices",
        "summary": "WGCSD lockdown drill initiated/complete notices were not added because they were already completed and did not require action."
      }
    ]
  }
};
